window.MathJax = {
    options: {
	skipHtmlTags: ['script', 'noscript', 'style', 'textarea', 'pre'],
	ignoreHtmlClass: 'tex2jax_ignore',
	processHtmlClass: 'tex2jax_process',
	includeHtmlTags: {
	    br: '\\\\',
	},
    },
    tex: {
	inlineMath: [['$','$'], ['\\(','\\)']],
	processEscapes: true,
	macros: {
	    // NOTATION
	    eqdef: "\\stackrel{\\smash{\\small\\mathsf{def}}}=",
	    set: ["{\\{#1\\}}", 1],
	    tparens: ["{\\toparen#1\\tcparen}", 1],
	    tbracks: ["{\\tobrack#1\\tcbrack}", 1],
	    tbraces: ["{\\tobrace#1\\tcbrace}", 1],
	    tstring: ["{\\tdquote\\mathtt{#1}\\tdquote}", 1],
	    ite:     ["#1~?~#2~:~#3", 3],
	    bN: "{\\mathbb{N}}",
	    es: "\\varepsilon",
	    // FUNCTIONS
	    len: ["{|#1|}", 1],
	    eclose: ["{\\mathrm{\\scriptstyle ECLOSE}(#1)}", 1],
	    first: "\\mathrm{\\scriptstyle FIRST}",
	    firstL: "\\first_{\\textit{libro}}",
	    follow: "\\mathrm{\\scriptstyle FOLLOW}",
	    predict: "\\mathrm{\\scriptstyle GUIDA}",
	    maybep: "\\mathrm{\\scriptstyle PAR}",
	    append: "\\mathbin{\\Vert}",
	    ap:     "\\mathbin{\\Vert}",
	    print:  "\\mathtt{print}",
	    // SYMBOLS
	    eos: "\\mathtt{\\$}",
	    tA: "{\\mathtt{a}}",
	    tB: "{\\mathtt{b}}",
	    tC: "{\\mathtt{c}}",
	    tskip: "{\\mathtt{skip}}",
	    ttIf: "{\\mathtt{if}}",
	    ttThen: "{\\mathtt{then}}",
	    ttElse: "{\\mathtt{else}}",
	    ttFi: "{\\mathtt{fi}}",
	    twhile: "{\\mathtt{while}}",
	    tdo:     "{\\mathtt{do}}",
	    tfor: "{\\mathtt{for}}",
	    treturn: "{\\mathtt{return}}",
	    tid: "{\\mathtt{id}}",
	    tdigit: "{\\mathbf{digit}}",
	    tnum: "{\\mathtt{n}}",
	    trel: "\\mathrel{\\textit{relop}}",
	    toparen: "{\\mathtt{(}}",
	    tcparen: "{\\mathtt{)}}",
	    tobrack: "{\\mathtt{[}}",
	    tcbrack: "{\\mathtt{]}}",
	    tobrace: "{\\verb'{'}",
	    tcbrace: "{\\verb'}'}",
	    tdquote: "{\\verb'\"'}",
	    tplus: "\\mathbin{\\mathtt{+}}",
	    tminus: "\\mathbin{\\verb'-'}",
	    ttimes: "\\mathbin{\\mathtt{*}}",
	    trem:   "\\mathbin{\\mathtt{\\\%}}",
	    tdiv:   "\\mathbin{\\mathtt{/}}",
	    tor:    "\\mathrel{\\mathtt{||}}",
	    tand:   "\\mathrel{\\mathtt{\\&\\&}}",
	    tnot:   "\\mathtt{!}",
	    timp:   "\\mathrel{\\mathtt{=>}}",
	    ttrue:  "\\mathtt{true}",
	    tfalse: "\\mathtt{false}",
	    tcomma: "{\\mathtt{,}}",
	    tsemi:  "{\\mathtt{;}}",
	    tqmark: "{\\mathtt{?}}",
	    tcolon: "{\\mathtt{:}}",
	    teq: "\\mathrel{\\mathtt{=}}",
	    teqq:   "\\mathrel{\\mathtt{{=}{=}}}",
	    tneq:   "\\mathrel{\\mathtt{{!}{=}}}",
	    tlt:    "\\mathrel{\\mathtt{<}}",
	    tgt:    "\\mathrel{\\mathtt{>}}",
	    tle:    "\\mathrel{\\mathtt{{<}{=}}}",
	    tge:    "\\mathrel{\\mathtt{{>}{=}}}",
	    // RELATIONS
	    derG: "\\Rightarrow_G",
	    wderG: "\\Rightarrow^\\ast_G",
	    der: "\\Rightarrow",
	    nder: "\\nRightarrow",
	    lder: "\\Rightarrow_{lm}",
	    rder: "\\Rightarrow_{rm}",
	    wder: "\\Rightarrow^\\ast",
	    nwder: "\\nRightarrow^\\ast",
	    wlder: "\\Rightarrow^\\ast_{lm}",
	    wrder: "\\Rightarrow^\\ast_{rm}",
	    moveP: "\\vdash_P",
	    wmoveP: "\\vdash^\\ast_P",
	    move: "\\vdash",
	    vmove: "\\top",
	    wmove: "\\vdash^\\ast",
	    null: "\\mathrm{\\scriptstyle NULL}",
	    // CLASSES
	    green: ["{\\class{green}{#1}}", 1],
	    red: ["{\\class{red}{#1}}", 1],
	    // SDD
	    val:  "\\textit{val}",
	    inh:  "\\textit{inh}",
	    post: "\\textit{post}",
	    code: "\\textit{code}",
	    emit: "\\textit{emit}",
	    true: "\\textit{true}",
	    false: "\\textit{false}",
	    ret:   "\\textit{ret}",
	    locals: "\\textit{locals}",
	    args:   "\\textit{args}",
	    stack:  "\\textit{stack}",
	    next:  "\\textit{next}",
	    newlabel: "\\textit{newlabel}",
	    address: ["\\mathtt{\\&}{#1}", 1 ],
	    Slist:   "S_{\\textit{list}}",
	    Elist:   "E_{\\textit{list}}",
	    Elistp:  "E_{\\textit{listp}}",
	    // JVM TYPES
	    TVOID:         "\\mathtt{void}",
	    TINT:          "\\mathtt{int}",
	    TFLOAT:        "\\mathtt{float}",
	    TDOUBLE:       "\\mathtt{double}",
	    TARRAY:        ["{#1}\\tbracks{}", 1],
	    TSTRING:       "\\mathtt{String}",
	    // JVM INSTRUCTIONS
	    ILABEL:        ["{#1}\\tcolon", 1],
	    IJUMP:         "\\mathtt{goto}",
	    IJUMPIF:       ["\\mathtt{if\\_icmp{#1}}", 1],
	    IILOAD:        "\\mathtt{iload}",
	    IISTORE:       "\\mathtt{istore}",
	    INEWARRAY:     "\\mathtt{newarray}",
	    IARRAYLOAD:    "\\mathtt{iaload}",
	    IARRAYSTORE:   "\\mathtt{iastore}",
	    IARRAYLENGTH:  "\\mathtt{arraylength}",
	    IINVOKESTATIC: "\\mathtt{invokestatic}",
	    IRETURN:       "\\mathtt{return}",
	    IIRETURN:      "\\mathtt{ireturn}",
	    ILDC:          "\\mathtt{ldc}",
	    IPOP:          "\\mathtt{pop}",
	    IDUP:          "\\mathtt{dup}",
	    ISWAP:         "\\mathtt{swap}",
	    IINEG:         "\\mathtt{ineg}",
	    IIADD:         "\\mathtt{iadd}",
	    IISUB:         "\\mathtt{isub}",
	    IIMUL:         "\\mathtt{imul}",
	    IIDIV:         "\\mathtt{idiv}",
	    IIREM:         "\\mathtt{irem}",
	    IIAND:         "\\mathtt{iand}",
	    IIOR:          "\\mathtt{ior}",
	},
	autoload: {
	    color: [],
	    colorV2: ['color']
	},
	packages: {'[+]': ['noerrors', 'html']}
    },
    loader: {
	load: ['[tex]/noerrors', '[tex]/html']
    }
};
